# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirdPartyHall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartyHall

  target 'ThirdPartyHallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThirdPartyHallUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'MBProgressHUD', '~> 1.1.0'
end
